tasks:
  - name : Dev
    before: npm i -g pnpm
    init: pnpm i && npm run build
    command: pnpm dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint

    - svelte.svelte-vscode

    - bradlc.vscode-tailwindcss

ports:
  - port: 3000
    visibility: public
