image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run db
    command : mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name : Dev
    before: npm i -g pnpm
    init: pnpm i
    command: pnpm dev
  
vscode:
  extensions:
    - dbaeumer.vscode-eslint

    - svelte.svelte-vscode

    - bradlc.vscode-tailwindcss

ports:
  - port: 3000
    visibility: public
